[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = " $title | - "

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20,rot_interval:0.20) |}"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %Y-%m-%d %H:%M:%S') "
